// import "./globals.css";
// import Navbar from "../components/Navbar";
// import Footer from "../components/Footer";
// import { Arimo } from "next/font/google";
// import { FaWhatsapp } from "react-icons/fa";
// import { Toaster } from "react-hot-toast";
// import { CartProvider } from "../context/CartContext";

// const arimo = Arimo({
//   subsets: ["latin"],
//   weight: ["400", "500", "600", "700"],
//   display: "swap",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`${arimo.className} bg-white`}>
//         <CartProvider>
//           {/* Navbar */}
//           <Navbar />

//           {/* Toaster */}
//           <Toaster position="top-right" toastOptions={{ duration: 3000 }} />

//           {/* Page Content */}
//           {children}

//           {/* Footer for all pages */}
//           <footer className="pb-6">
//             <Footer />
//           </footer>

//           {/* WhatsApp Support UI */}
//           <div className="fixed bottom-6 right-16 bg-white text-gray-600 text-sm p-2 rounded-lg shadow-lg animate-bounce z-50">
//             Any queries? Contact us!
//           </div>
//           <a
//             href={`https://wa.me/7744042929`}
//             className="fixed bottom-4 right-4 bg-green-500 text-white p-3 rounded-full shadow-lg hover:bg-green-600 transition-all duration-300 animate-bounce z-50"
//             target="_blank"
//             rel="noopener noreferrer"
//             style={{ filter: "drop-shadow(0 0 10px rgba(0,0,0,0.1))" }}
//           >
//             <FaWhatsapp size={24} />
//           </a>
//         </CartProvider>
//       </body>
//     </html>
//   );
// }








import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import { Arimo } from "next/font/google";
import { FaWhatsapp } from "react-icons/fa";
import { Toaster } from "react-hot-toast";
import { CartProvider } from "../context/CartContext";
import CategoryWrapper from "../components/CategoryWrapper"; // client component

const arimo = Arimo({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata = {
  title: "LGM Sports",
  description: "LGM Sports",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${arimo.className} bg-white`}>
        <CartProvider>
          <Navbar />
          <CategoryWrapper /> {/* Client logic here */}
          <Toaster position="top-right" toastOptions={{ duration: 3000 }} />
          {children}
          <footer >
            <Footer />
          </footer>
          <div className="fixed bottom-6 right-16 bg-white text-gray-600 text-sm p-2 rounded-lg shadow-lg animate-bounce z-50">
            Any queries? Contact us!
          </div>
          <a
            href={`https://wa.me/7744042929`}
            className="fixed bottom-4 right-4 bg-green-500 text-white p-3 rounded-full shadow-lg hover:bg-green-600 transition-all duration-300 animate-bounce z-50"
            target="_blank"
            rel="noopener noreferrer"
            style={{ filter: "drop-shadow(0 0 10px rgba(0,0,0,0.1))" }}
          >
            <FaWhatsapp size={24} />
          </a>
        </CartProvider>
      </body>
    </html>
  );
}
